sudo: false
language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - $HOME/.m2
script: sh -c 'cd backend && mvn clean package'

notifications:
  slack: bls-patronage-2016:6bKFdmvLz1nOJEtszzVg2RLn
